using LGBApp.Backend.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace LGBApp.Backend.Services;

public static class InvoicePdfService
{
    static InvoicePdfService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] Build(Invoice invoice, Customer customer)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text("LGB Services").Bold().FontSize(18);
                    col.Item().Text("Tax Invoice / Invoice").FontSize(14).FontColor(Colors.Grey.Darken2);
                });

                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Spacing(8);
                    col.Item().Text($"Invoice No: {invoice.InvoiceNumber}").Bold();
                    col.Item().Text($"Status: {invoice.Status}");
                    col.Item().Text($"Date: {(invoice.IssuedAt ?? invoice.CreatedAt):yyyy-MM-dd}");

                    col.Item().PaddingTop(16).Text("Bill to").Bold();
                    col.Item().Text(customer.Company);
                    if (!string.IsNullOrWhiteSpace(customer.Name))
                        col.Item().Text(customer.Name);
                    if (!string.IsNullOrWhiteSpace(customer.Email))
                        col.Item().Text(customer.Email);

                    col.Item().PaddingTop(20).Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(3);
                            c.RelativeColumn(1);
                        });
                        table.Header(h =>
                        {
                            h.Cell().BorderBottom(1).Padding(4).Text("Description").Bold();
                            h.Cell().BorderBottom(1).Padding(4).AlignRight().Text("Amount").Bold();
                        });
                        table.Cell().Padding(4).Text(string.IsNullOrWhiteSpace(invoice.Notes)
                            ? "Professional services"
                            : invoice.Notes!);
                        table.Cell().Padding(4).AlignRight()
                            .Text($"{invoice.Currency} {invoice.Amount:N2}");
                    });

                    col.Item().PaddingTop(12).AlignRight()
                        .Text($"Total: {invoice.Currency} {invoice.Amount:N2}").Bold().FontSize(13);
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by LGB Services · ");
                    t.Span($"{DateTime.UtcNow:yyyy-MM-dd} UTC").FontColor(Colors.Grey.Medium);
                });
            });
        });

        return doc.GeneratePdf();
    }
}
