// <auto-generated />
using System;
using LGBApp.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LGBApp.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714093648_Review2_FormConcurrencyStamp")]
    partial class Review2_FormConcurrencyStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LGBApp.Backend.Models.AccountHolder", b =>
                {
                    b.Property<int>("AccountHolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClientAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsMoa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsMoi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsMoiApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountHolderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountHolders");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.AppNotification", b =>
                {
                    b.Property<int>("AppNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppNotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("AppNotifications");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.BillingParty", b =>
                {
                    b.Property<int>("BillingPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("BillingPartyId");

                    b.ToTable("BillingParties");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.CompletedService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobAssignedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedQty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateCompleted");

                    b.HasIndex("JobRequestId");

                    b.ToTable("CompletedServices");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargeTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargeToPartyIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cosec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DivisionGroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceByPartyIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("LastContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaHoldersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoaFormTemplateCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoaWorkflowTemplateCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoiApprovalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoiApprovalMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("AllRequired");

                    b.Property<string>("MoiFormTemplateCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoiJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PackageValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.CustomerPackage", b =>
                {
                    b.Property<int>("CustomerPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PackageValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("PricingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Validity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerPackageId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerPackages", (string)null);
                });

            modelBuilder.Entity("LGBApp.Backend.Models.DivisionGroup", b =>
                {
                    b.Property<int>("DivisionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMoaFormTemplateCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMoiFormTemplateCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoaWorkflowTemplateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("DivisionGroupId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DivisionGroups");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.DivisionGroupRecommender", b =>
                {
                    b.Property<int>("DivisionGroupRecommenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DivisionGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DivisionGroupRecommenderId");

                    b.HasIndex("DivisionGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("DivisionGroupRecommenders");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.FormTemplate", b =>
                {
                    b.Property<int>("FormTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuerEntity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FormTemplateId");

                    b.HasIndex("FormType", "Code")
                        .IsUnique();

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("JobRequestId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobItemDocument", b =>
                {
                    b.Property<int>("JobItemDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRequestUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VisibleToInternal")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobItemDocumentId");

                    b.HasIndex("JobRequestId");

                    b.HasIndex("JobRequestUnitId");

                    b.ToTable("JobItemDocuments");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequest", b =>
                {
                    b.Property<int>("JobRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountHolderEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountHolderPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalHandoffStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobAssignedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedQty")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobRequestId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerPackageId");

                    b.HasIndex("Status");

                    b.ToTable("JobRequests");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequestUnit", b =>
                {
                    b.Property<int>("JobRequestUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalHandoffStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PackageScheduleItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobRequestUnitId");

                    b.HasIndex("JobRequestId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("JobRequestUnits");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequestUnitAssignee", b =>
                {
                    b.Property<int>("JobRequestUnitAssigneeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobRequestUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobRequestUnitAssigneeId");

                    b.HasIndex("UserId");

                    b.HasIndex("JobRequestUnitId", "UserId")
                        .IsUnique();

                    b.ToTable("JobRequestUnitAssignees");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.MOAForm", b =>
                {
                    b.Property<int>("MOAFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BankSignatoryMatter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientApprovalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinanceRelated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormTemplateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRequestUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MOIFormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackChecklistJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<bool>("ShareMovement")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SharonApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedForAdminReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MOAFormId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobRequestId");

                    b.HasIndex("JobRequestUnitId");

                    b.HasIndex("MOIFormId");

                    b.ToTable("MOAForms");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.MOIForm", b =>
                {
                    b.Property<int>("MOIFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BankSignatoryMatter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientApprovalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinanceRelated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormTemplateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRequestUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendationComments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecommendedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecommendedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MOIFormId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobRequestId");

                    b.HasIndex("JobRequestUnitId");

                    b.ToTable("MOIForms");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.PackageScheduleItem", b =>
                {
                    b.Property<int>("PackageScheduleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobRequestUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PackageScheduleItemId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerPackageId");

                    b.ToTable("PackageScheduleItems");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.PasswordResetOtp", b =>
                {
                    b.Property<int>("PasswordResetOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PasswordResetOtpId");

                    b.HasIndex("Email", "CreatedAt");

                    b.ToTable("PasswordResetOtps");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AddOnPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddOnQuantitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddOnsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AddOnsQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PackagePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtyPerYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceQuantitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServicesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.ServiceJobForm", b =>
                {
                    b.Property<int>("ServiceJobFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceJobFormId");

                    b.HasIndex("JobRequestId")
                        .IsUnique();

                    b.ToTable("ServiceJobForms");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.SignatoryCustomerAccess", b =>
                {
                    b.Property<int>("SignatoryCustomerAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SignatoryCustomerAccessId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId", "CustomerId")
                        .IsUnique();

                    b.ToTable("SignatoryCustomerAccess");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanApproveMoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanApproveMoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanApproveMoiIntake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanRecommendMoi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvitedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternalSignatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User");

                    b.HasKey("UserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowInstance", b =>
                {
                    b.Property<int>("WorkflowInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MoaFormId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MoiFormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowInstanceId");

                    b.HasIndex("MoaFormId");

                    b.HasIndex("MoiFormId");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowStepInstance", b =>
                {
                    b.Property<int>("WorkflowStepInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdminOverridden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssigneeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssigneeUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverriddenByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowStepInstanceId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowStepInstances");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowStepTemplate", b =>
                {
                    b.Property<int>("WorkflowStepTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAdminOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssigneeDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssigneeUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowStepTemplateId");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("WorkflowStepTemplates");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowTemplate", b =>
                {
                    b.Property<int>("WorkflowTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowTemplateId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkflowTemplates");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.AccountHolder", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany("AccountHolders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGBApp.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.CustomerPackage", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany("Packages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.DivisionGroupRecommender", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.DivisionGroup", "DivisionGroup")
                        .WithMany("Recommenders")
                        .HasForeignKey("DivisionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGBApp.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DivisionGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.Invoice", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LGBApp.Backend.Models.JobRequest", "JobRequest")
                        .WithMany()
                        .HasForeignKey("JobRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobItemDocument", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.JobRequest", "JobRequest")
                        .WithMany()
                        .HasForeignKey("JobRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGBApp.Backend.Models.JobRequestUnit", "JobRequestUnit")
                        .WithMany()
                        .HasForeignKey("JobRequestUnitId");

                    b.Navigation("JobRequest");

                    b.Navigation("JobRequestUnit");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequest", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "CustomerRecord")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGBApp.Backend.Models.CustomerPackage", "CustomerPackage")
                        .WithMany()
                        .HasForeignKey("CustomerPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomerPackage");

                    b.Navigation("CustomerRecord");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequestUnit", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.JobRequest", "JobRequest")
                        .WithMany("Units")
                        .HasForeignKey("JobRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequestUnitAssignee", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.JobRequestUnit", "Unit")
                        .WithMany("Assignees")
                        .HasForeignKey("JobRequestUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGBApp.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.MOAForm", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGBApp.Backend.Models.JobRequest", "JobRequest")
                        .WithMany()
                        .HasForeignKey("JobRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGBApp.Backend.Models.JobRequestUnit", "JobRequestUnit")
                        .WithMany()
                        .HasForeignKey("JobRequestUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGBApp.Backend.Models.MOIForm", "MOIForm")
                        .WithMany()
                        .HasForeignKey("MOIFormId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("JobRequest");

                    b.Navigation("JobRequestUnit");

                    b.Navigation("MOIForm");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.MOIForm", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGBApp.Backend.Models.JobRequest", "JobRequest")
                        .WithMany()
                        .HasForeignKey("JobRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGBApp.Backend.Models.JobRequestUnit", "JobRequestUnit")
                        .WithMany()
                        .HasForeignKey("JobRequestUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("JobRequest");

                    b.Navigation("JobRequestUnit");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.PackageScheduleItem", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGBApp.Backend.Models.CustomerPackage", "CustomerPackage")
                        .WithMany()
                        .HasForeignKey("CustomerPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerPackage");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.ServiceJobForm", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.JobRequest", "JobRequest")
                        .WithMany()
                        .HasForeignKey("JobRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.SignatoryCustomerAccess", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGBApp.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.User", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowInstance", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.MOAForm", "MoaForm")
                        .WithMany()
                        .HasForeignKey("MoaFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LGBApp.Backend.Models.MOIForm", "MoiForm")
                        .WithMany()
                        .HasForeignKey("MoiFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LGBApp.Backend.Models.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoaForm");

                    b.Navigation("MoiForm");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowStepInstance", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowStepTemplate", b =>
                {
                    b.HasOne("LGBApp.Backend.Models.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.Customer", b =>
                {
                    b.Navigation("AccountHolders");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.DivisionGroup", b =>
                {
                    b.Navigation("Recommenders");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequest", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.JobRequestUnit", b =>
                {
                    b.Navigation("Assignees");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowInstance", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("LGBApp.Backend.Models.WorkflowTemplate", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
